name: Ubuntu 

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      

      - name: Install Depencies
        run: |
          sudo apt update
          sudo apt install openssh-server firefox xfce4 xfce4-goodies dbus-x11 dbus-user-session git tightvncserver curl openvpn  -y

      - name: Essentials
        run: |
          echo 'runner:P@ssw0rd1123' | sudo chpasswd
          sudo mkdir -p /run/sshd && sudo systemctl restart ssh
          sudo systemctl status ssh
          sudo chmod 600 ./debug.ovpn
      
      - name: Essentials2
        run: |
          mkdir -p ~/.vnc

          printf '%s\n' 'P@ssw0rd1123' | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          tightvncserver -geometry 1920x1080 


      - name: Start session
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --auth-key=tskey-auth-k1Cq41aLVB21CNTRL-ekx6kdVSr4e9g3m5VCWX4eFPkw9pT7TvW --advertise-exit-node
          sudo tailscale up
          sudo tailscale status
          echo "Keeping process alive for 6 hours..."
          sleep 6h
          echo "6 hours completed."
