name: Ubuntu 

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      

      - name: Install Depencies
        run: |
          sudo apt update
          sudo apt install openssh-server firefox xfce4 xfce4-goodies dbus-x11 dbus-user-session git tigervnc-standalone-server  tigervnc-common curl openvpn  -y

      - name: Essentials
        run: |
          echo 'runner:P@ssw0rd1123' | sudo chpasswd
          sudo mkdir -p /run/sshd && sudo systemctl restart ssh
          sudo systemctl status ssh
          sudo chmod 600 ./debug.ovpn
      
      - name: Essentials2
        run: |
          mkdir -p ~/.vnc

          printf '%s\n' 'P@ssw0rd1123' | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver -geometry 1920x1080 -depth 32 -localhost no


      - name: Start session
        run: |
          sudo modprobe tun
          ls -l /dev/net/tun
          sudo openvpn --config debug.ovpn
